
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('accounts').del()
    .then(function () {
      // Inserts seed entries
      return knex('accounts').insert([
        {description: 'GL FOR UNKNOWN ACCOUNTS', natural: '999999', module: 'Suspense'},
        {description: 'Bank of America', natural: '110011', module: 'Cash'},
        {description: 'Wells Fargo', natural: '110012', module: 'Cash'},
        {description: 'Chase', natural: '110013', module: 'Cash'},
        {description: 'Money Market Account', natural: '110014', module: 'Cash'},
        {description: 'ACH In', natural: '110020', module: 'Cash'},
        {description: 'ACH Out', natural: '110030', module: 'Cash'},
        {description: 'Checks In', natural: '110040', module: 'Cash'},
        {description: 'Checks Out', natural: '110050', module: 'Cash'},
        {description: 'Wire In', natural: '110060', module: 'Cash'},
        {description: 'Wire Out', natural: '110070', module: 'Cash'},
        {description: 'A/R - TRADE', natural: '120010', module: 'Accounts Receivable'},
        {description: 'A/R - RENT', natural: '120015', module: 'Accounts Receivable'},
        {description: 'A/R - WIP', natural: '120016', module: 'Accounts Receivable'},
        {description: 'A/R - ALLOWANCE FOR BAD DEBT', natural: '122510', module: 'Accounts Receivable'},
        {description: 'A/R - DUE FROM EMPLOYEES', natural: '123210', module: 'Accounts Receivable'},
        {description: 'A/R - OTHER', natural: '123510', module: 'Accounts Receivable'},
        {description: 'A/R - EMPLOYEE PAYROLL', natural: '123810', module: 'Accounts Receivable'},
        {description: 'A/R - EMPLOYEE PAYROLL-EXECUTIVE-', natural: '123811', module: 'Accounts Receivable'},
        {description: 'I/C - DUE FROM EVOLUTION PAYROLL', natural: '127000', module: 'Accounts Receivable'},
        {description: 'INTERNAL IC ACCOUNT', natural: '127100', module: 'Accounts Receivable'},
        {description: 'IC A/R COMPASS', natural: '127125', module: 'Accounts Receivable'},
        {description: 'IC A/R MANGROVE', natural: '127127', module: 'Accounts Receivable'},
        {description: 'IC A/R - FORGENT CANADA', natural: '127150', module: 'Accounts Receivable'},
        {description: 'IC-RESERVE CANADA PAYABLE', natural: '127156', module: 'Accounts Receivable'},
        {description: 'IC - A/R - INDIA', natural: '127160', module: 'Accounts Receivable'},
        {description: 'IC A/R Asure UK', natural: '127829', module: 'Accounts Receivable'},
        {description: 'WIP - AUSTIN/DEPOT WIP', natural: '130510', module: 'Inventory'},
        {description: 'INVENTORY - FINISHED GOODS', natural: '131510', module: 'Inventory'},
        {description: 'INVENTORY - HAAS', natural: '131525', module: 'Inventory'},
        {description: 'INVENTORY - OTHER', natural: '132570', module: 'Inventory'},
        {description: 'INVENTORY - OTHER - AIRCLOCK', natural: '132571', module: 'Inventory'},
        {description: 'INVENTORY RESERVES - FINISHED GOODS', natural: '133040', module: 'Inventory'},
        {description: 'PREPAID EXPS - VENDOR', natural: '140010', module: 'Prepaid Expense'},
        {description: 'PREPAID PURCHASE ORDERS', natural: '140015', module: 'Prepaid Expense'},
        {description: 'PREPAID EXPS - INSUR', natural: '140030', module: 'Prepaid Expense'},
        {description: 'PREPAID - DEPOSITS', natural: '140040', module: 'Prepaid Expense'},
        {description: 'FIXED ASSET - COMPUTERS', natural: '155000', module: 'Fixed Asset'},
        {description: 'F/A CLEARING - COMPUTERS', natural: '155010', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - SOFTWARE', natural: '155100', module: 'Fixed Asset'},
        {description: 'F/A CLEARING - SOFTWARE', natural: '155110', module: 'Fixed Asset'},
        {description: 'FIXED ASSETS - LEGIANT ACQUISITION', natural: '155180', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - EQUIPMENT', natural: '155200', module: 'Fixed Asset'},
        {description: 'F/A CLEARING - EQUIPMENT', natural: '155210', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - OFFICE EQUIPMENT', natural: '155300', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - FURNITURE', natural: '155400', module: 'Fixed Asset'},
        {description: 'F/A CLEARING - FURNITURE', natural: '155410', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - LEASEHOLD IMPROV', natural: '155500', module: 'Fixed Asset'},
        {description: 'F/A CLEARING - LEASEHOLD IMPROV', natural: '155510', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - HAAS', natural: '155650', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - CAPITAL LEASES', natural: '156000', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - IN HOUSE ISE', natural: '157000', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - FIELD ISE', natural: '157100', module: 'Fixed Asset'},
        {description: 'FIXED ASSET - TEST ISE', natural: '157200', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - TOOLING', natural: '164000', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - COMPUTERS', natural: '165000', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - SOFTWARE', natural: '165100', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - EQUIPMENT', natural: '165200', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - OFFICE EQUIPMENT', natural: '165300', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - FURNITURE', natural: '165400', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - LEASEHOLD IMPROV', natural: '165500', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - CAPITAL ASSET', natural: '166000', module: 'Fixed Asset'},
        {description: 'ACCUM DEPREC - ISE', natural: '167000', module: 'Fixed Asset'},
        {description: 'INVESTMENT IN SUB - UK', natural: '170300', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - PAY SYSTEMS', natural: '170510', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - SAVERS', natural: '170520', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - TELEPAYROLL', natural: '170530', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - INDIA', natural: '170550', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN ISYSTEMS', natural: '170750', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN COMPASS', natural: '170755', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN ADS', natural: '170760', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - PEOPLECUBE', natural: '170900', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - WELLS FARGO PAYROLL', natural: '170901', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - AUSTIN HR', natural: '170902', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - OCCUPEYE', natural: '170903', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - US PAYROLL', natural: '170904', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUB - MOSAIC', natural: '170905', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN SUBS - MANGROVE', natural: '170950', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN CORPORATE PAYROLL, INC.', natural: '170960', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN PAYROLL SPECIALTIES NW, INC.', natural: '170970', module: 'Subsidiary Investment'},
        {description: 'INVESTMENT IN PERSONNEL MANAGEMENT SYSTEMS, INC.', natural: '170980', module: 'Subsidiary Investment'},
        {description: 'Accumulated Amortization', natural: '172200', module: 'Intangibles'},
        {description: 'INTANGIBLE ASSETS - ACCUM AMORT OTHER', natural: '175025', module: 'Intangibles'},
        {description: 'GOODWILL', natural: '177000', module: 'Intangibles'},
        {description: 'INTANGIBLE ASSETS - IEMPLOYEE ACQUISITION', natural: '177001', module: 'Intangibles'},
        {description: 'INTANGIBLE ASSETS - FOTOPUNCH', natural: '177002', module: 'Intangibles'},
        {description: 'INTANGIBLE ASSETS - ROOMTAG', natural: '177003', module: 'Intangibles'},
        {description: 'INTANGIBLE ASSETS - LEGIANT', natural: '177008', module: 'Intangibles'},
        {description: 'INTANGIBLE ASSETS - PC', natural: '177009', module: 'Intangibles'},
        {description: 'INTANGIBLE ASSETS - LEGIANT ACCUM AMORT', natural: '177108', module: 'Intangibles'},
        {description: 'A/P - TRADE', natural: '211000', module: 'Accounts Payable'},
        {description: 'A/P - RBNI - RECD NOT INVOICED', natural: '212000', module: 'Accounts Payable'},
        {description: 'IC A/P - AUSTRALIA - SERVICE FEE', natural: '213200', module: 'Accounts Payable'},
        {description: 'IC A/P - INVENTORY', natural: '213300', module: 'Accounts Payable'},
        {description: 'IC A/P - INDIA', natural: '213402', module: 'Accounts Payable'},
        {description: 'IC - RESERVE INDIA PAYABLE', natural: '213403', module: 'Accounts Payable'},
        {description: 'A/P - OTHER', natural: '215100', module: 'Accounts Payable'},
        {description: 'A/P - CUSTOMER REFUNDS', natural: '215120', module: 'Accounts Payable'},
        {description: 'A/P - OTHER MISC', natural: '215130', module: 'Accounts Payable'},
        {description: 'A/P - CLEARING', natural: '215150', module: 'Accounts Payable'},
        {description: 'A/P - ACCRUED DIRECTORS FEES', natural: '215300', module: 'Accounts Payable'},
        {description: 'ACCRUED LIABILITY - PAYROLL', natural: '231100', module: 'Payroll'},
        {description: 'ACCR PAY TAX', natural: '231200', module: 'Payroll'},
        {description: 'ACCRUED LIABILITY - FIT PAYABLE', natural: '231210', module: 'Payroll'},
        {description: 'ACCRUED LIABILTY - FICA EMPLOYEE', natural: '231220', module: 'Payroll'},
        {description: 'ACCRUED LIABILITY - FICA EMPLOYER EXP', natural: '231230', module: 'Payroll'},
        {description: 'MEDICARE', natural: '231240', module: 'Payroll'},
        {description: 'STATE W/H', natural: '231250', module: 'Payroll'},
        {description: 'ACCRUED LIABILITY - BONUSES', natural: '231500', module: 'Payroll'},
        {description: 'ACCRUED LIABILITY - HEALTH', natural: '231600', module: 'Payroll'},
        {description: 'PAYROLL GARNISHMENT-EXECUTIVE-', natural: '231650', module: 'Payroll'},
        {description: '401K EMPLOYEE DEDUCTION', natural: '231700', module: 'Payroll'},
        {description: 'ACCRUED LIABILTY-FLEXIBLE SPENDING', natural: '231900', module: 'Payroll'},
        {description: 'ACCRUED SEVERANCE', natural: '231950', module: 'Payroll'},
        {description: 'ACCRUED LIABILITY-SUPPLEMENTAL LIFE INSURANCE', natural: '232000', module: 'Payroll'},
        {description: 'ACCRUED LEGAL EXPS', natural: '232100', module: 'Legal'},
        {description: 'RETURN/REFUND LIABILITY', natural: '232222', module: 'Tax'},
        {description: 'ACCRUED AUDIT', natural: '232300', module: 'Other Liability'},
        {description: 'ACCRUED EXP - OTHER', natural: '232900', module: 'Other Liability'},
        {description: 'ACCRUED INTEREST PAYABLE', natural: '233100', module: 'Debt'},
        {description: 'LT - INTEREST PAYABLE', natural: '233105', module: 'Debt'},
        {description: 'FEDERAL INC TAX', natural: '235100', module: 'Tax'},
        {description: 'DEFERRED TAX LIABILITY', natural: '235125', module: 'Tax'},
        {description: 'TEXAS GROSS RECEIPTS TAX ACCRUAL', natural: '235150', module: 'Tax'},
        {description: 'STATE INC TAX', natural: '235200', module: 'Tax'},
        {description: 'PROPERTY AND OTHER TAXES', natural: '235250', module: 'Tax'},
        {description: 'STATE FRANCHISE TAX', natural: '235300', module: 'Tax'},
        {description: 'PROPERTY TAX-WILD BASIN', natural: '236100', module: 'Tax'},
        {description: 'PROPERTY TAX-OTHER', natural: '236300', module: 'Tax'},
        {description: 'USE TAX - CA', natural: '238040', module: 'Tax'},
        {description: 'USE TAX - MA', natural: '238180', module: 'Tax'},
        {description: 'USE TAX - MI', natural: '238210', module: 'Tax'},
        {description: 'USE TAX - TX', natural: '238390', module: 'Tax'},
        {description: 'SALES TAX - UNDEFINED', natural: '239000', module: 'Tax'},
        {description: 'SALES TAX - AL', natural: '239010', module: 'Tax'},
        {description: 'SALES TAX - AZ', natural: '239030', module: 'Tax'},
        {description: 'SALES TAX - CA', natural: '239040', module: 'Tax'},
        {description: 'SALES TAX - CT', natural: '239060', module: 'Tax'},
        {description: 'SALES TAX - DC', natural: '239070', module: 'Tax'},
        {description: 'SALES TAX - FL', natural: '239080', module: 'Tax'},
        {description: 'SALES TAX - IL', natural: '239130', module: 'Tax'},
        {description: 'SALES TAX - LA', natural: '239170', module: 'Tax'},
        {description: 'SALES TAX - MA', natural: '239180', module: 'Tax'},
        {description: 'SALES TAX - MD', natural: '239190', module: 'Tax'},
        {description: 'SALES TAX - ME', natural: '239200', module: 'Tax'},
        {description: 'SALES TAX - MI', natural: '239210', module: 'Tax'},
        {description: 'SALES TAX - MN', natural: '239220', module: 'Tax'},
        {description: 'SALES TAX - MO', natural: '239230', module: 'Tax'},
        {description: 'SALES TAX - MS', natural: '239240', module: 'Tax'},
        {description: 'SALES TAX - NH', natural: '239275', module: 'Tax'},
        {description: 'SALES TAX - NJ', natural: '239280', module: 'Tax'},
        {description: 'SALES TAX - NY', natural: '239310', module: 'Tax'},
        {description: 'SALES TAX - RI', natural: '239350', module: 'Tax'},
        {description: 'SALES TAX - TX', natural: '239390', module: 'Tax'},
        {description: 'SALES TAX - WA', natural: '239430', module: 'Tax'},
        {description: 'Sales Tax- Canada Toronto', natural: '239520', module: 'Tax'},
        {description: 'N/P - LEASE - CURRENT PORTION', natural: '240100', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-COACTIV', natural: '240101', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-IBM', natural: '240102', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-LEAF', natural: '240103', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-LONDON', natural: '240104', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-M2', natural: '240105', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-WESTERN', natural: '240106', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-DELL LAPTOPS', natural: '240107', module: 'Capital Lease'},
        {description: 'N/P - ADI DEBT- CURRENT', natural: '240108', module: 'Note Payable'},
        {description: 'CAP LEASE-CURR-DIRECT CAPITAL', natural: '240109', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-VAR RESOURCES', natural: '240110', module: 'Capital Lease'},
        {description: 'CAP LEASE-CURR-VAR RESOURCES#2', natural: '240111', module: 'Capital Lease'},
        {description: 'CAP Lease Dell Contract 167', natural: '240112', module: 'Capital Lease'},
        {description: 'Capital lease obligation - ST', natural: '240113', module: 'Note Payable'},
        {description: 'Capital lease obligation - LT', natural: '240114', module: 'Note Payable'},
        {description: 'N/P - LEASE - NON-CURRENT PORTION', natural: '240200', module: 'Note Payable'},
        {description: 'NOTES PAYABLE-WELLS FARGO', natural: '240213', module: 'Note Payable'},
        {description: 'iSystems Long Terrm Note Payable', natural: '240225', module: 'Note Payable'},
        {description: 'TelePayroll LT Note', natural: '240226', module: 'Note Payable'},
        {description: 'Savers LT Note', natural: '240228', module: 'Note Payable'},
        {description: 'Compass LT Note Payable', natural: '240230', module: 'Note Payable'},
        {description: 'ADS LT Note Payble', natural: '240235', module: 'Note Payable'},
        {description: 'N/P - ADI DEBT- CURRENT', natural: '240308', module: 'Note Payable'},
        {description: 'N/P--CURRENT', natural: '240309', module: 'Note Payable'},
        {description: 'iSystems Short Term Note Payable', natural: '240315', module: 'Note Payable'},
        {description: 'N/P - CPI Short Term', natural: '240320', module: 'Note Payable'},
        {description: 'N/P PMSI Short Term', natural: '240321', module: 'Note Payable'},
        {description: 'NP PSNW Short Term', natural: '240322', module: 'Note Payable'},
        {description: 'PaySystems ST Note', natural: '240327', module: 'Note Payable'},
        {description: 'Savers ST Note', natural: '240328', module: 'Note Payable'},
        {description: 'Compass Short Term Note Payable', natural: '240330', module: 'Note Payable'},
        {description: 'ADS ST Note Payable', natural: '240335', module: 'Note Payable'},
        {description: 'AUSTIN HR N/P SHORT-TERM', natural: '240345', module: 'Note Payable'},
        {description: 'Deffered revenue 3 -RESOURCE SCHEDULER', natural: '250100', module: 'Deferred Revenue'},
        {description: 'DEFERRED REV - CUR-NETSIM', natural: '250101', module: 'Deferred Revenue'},
        {description: 'DEF REV CURRENT NETSIM ONDEMAND', natural: '250102', module: 'Deferred Revenue'},
        {description: 'DEF REV CURRENT NETSIM TRAINING', natural: '250105', module: 'Deferred Revenue'},
        {description: 'DEF REV CURRENT IEMP TRAINING', natural: '250106', module: 'Deferred Revenue'},
        {description: 'DEF REV CURRENT IEMP SOFTWARE', natural: '250107', module: 'Deferred Revenue'},
        {description: 'DEF REV CURRENT SUBSCRIPTION', natural: '250108', module: 'Deferred Revenue'},
        {description: 'DEF REV CURRENT PROF SVCS', natural: '250109', module: 'Deferred Revenue'},
        {description: 'DEFERRED REV - TRANSFER TO CURRENT', natural: '250110', module: 'Deferred Revenue'},
        {description: 'DEFERRED REV - CLEAR-NETSIM', natural: '250111', module: 'Deferred Revenue'},
        {description: 'DEF REV CLEARING NETSIM ONDEMAND', natural: '250112', module: 'Deferred Revenue'},
        {description: 'DEFFERED REVENUE-PENDING IEMP', natural: '250113', module: 'Deferred Revenue'},
        {description: 'DEFFERED REVENUE-PENDING NETSIM', natural: '250114', module: 'Deferred Revenue'},
        {description: 'DEF REV CLEARING NETSIM TRAINING', natural: '250115', module: 'Deferred Revenue'},
        {description: 'DEF REV CLEARING IEMP SOFTWARE', natural: '250117', module: 'Deferred Revenue'},
        {description: 'DEF REV CLEARING SUBSCRIPTION- -RESOURCE SCHEDULER', natural: '250118', module: 'Deferred Revenue'},
        {description: 'DEF REV CLEARING PS OD', natural: '250119', module: 'Deferred Revenue'},
        {description: 'DEFERRED REVENUE VSOE', natural: '250125', module: 'Deferred Revenue'},
        {description: 'DEFERRED REVENUE ROOMTAG', natural: '250126', module: 'Deferred Revenue'},
        {description: 'DEFERRED REVENUE FOTOPUNCH', natural: '250127', module: 'Deferred Revenue'},
        {description: 'DEFERRED REVENUE - PROGRESS BILLINGS', natural: '250130', module: 'Deferred Revenue'},
        {description: 'DEFERRED REVENUE LEGIANT PENDING BILLINGS', natural: '250150', module: 'Deferred Revenue'},
        {description: 'CUST DEPOSITS - OTHER', natural: '250200', module: 'Deferred Revenue'},
        {description: 'Debt Finance Cost', natural: '250250', module: 'Debt'},
        {description: 'Unapplied Cash', natural: '250275', module: 'Accounts Receivable'},
        {description: 'DEF REV - LT SW MAINT', natural: '250400', module: 'Deferred Revenue'},
        {description: 'C/S - COMMON STOCK', natural: '290100', module: 'Equity'},
        {description: 'INTERCOMPANY STOCK', natural: '291992', module: 'Equity'},
        {description: 'APIC - COMMON STOCK', natural: '294100', module: 'Equity'},
        {description: 'APIC - INTEL', natural: '294200', module: 'Equity'},
        {description: 'CS-ISSUANCE COST', natural: '294299', module: 'Equity'},
        {description: 'UNREALIZED GAIN/(LOSS)', natural: '294700', module: 'Equity'},
        {description: 'TREASURY STOCK', natural: '296100', module: 'Equity'},
        {description: 'CONTRIBUTED CAPITAL', natural: '296200', module: 'Equity'},
        {description: 'CS - ISSUANCE COST', natural: '298100', module: 'Equity'},
        {description: 'UNDEFINED - DISC OPS', natural: '298199', module: 'Equity'},
        {description: 'RE - PRIOR PERIODS', natural: '298200', module: 'Equity'},
        {description: 'RETAINED EARNINGS - 606 ADJUSTMENT', natural: '298222', module: 'Equity'},
        {description: 'RE - NETSIMPLICITY MERGE UP', natural: '298250', module: 'Equity'},
        {description: 'RE - ARTICULEARN MERGE UP', natural: '298251', module: 'Equity'},
        {description: 'RE - ONSCREEN MERGE UP', natural: '298252', module: 'Equity'},
        {description: 'RE - FRANCE MERGE UP', natural: '298253', module: 'Equity'},
        {description: 'RE - IEMPLOYEE MERGE UP', natural: '298254', module: 'Equity'},
        {description: 'RE - CLI MERGE UP', natural: '298255', module: 'Equity'},
        {description: 'RE - AUSTRALIA MERGE UP', natural: '298256', module: 'Equity'},
        {description: 'RE - GERMANY MERGE UP', natural: '298257', module: 'Equity'},
        {description: 'RE - MMUS MERGE UP', natural: '298258', module: 'Equity'},
        {description: 'RE - CUMULATIVE TRANSLATION', natural: '298300', module: 'Equity'},
        {description: 'RE - RESERVE CTA', natural: '298301', module: 'Equity'},
        {description: 'RE - ISSUING TREASURY STOCK', natural: '298400', module: 'Equity'},
        {description: 'PRODUCT REV TRADE', natural: '310003', module: 'Revenue'},
        {description: 'PRODUCT RENTAL REVENUE', natural: '310005', module: 'Revenue'},
        {description: 'SOFTWARE REV TRADE ROYALTIES', natural: '380001', module: 'Revenue'},
        {description: 'SOFTWARE REV TRADE ON PREM', natural: '380003', module: 'Revenue'},
        {description: 'SOFTWARE REV TRADEMRM OD-OTHER', natural: '380010', module: 'Revenue'},
        {description: 'RESOURCE SCHEDULER', natural: '380050', module: 'Revenue'},
        {description: 'SERVICE REVENUE - OVERAGES', natural: '380065', module: 'Revenue'},
        {description: 'SERVICE REVENUE ON DEMAND', natural: '380075', module: 'Revenue'},
        {description: 'SERVICE REVENUE - EXIT PACKAGE', natural: '380078', module: 'Revenue'},
        {description: 'MSSW - SFTW CONTRACTS REV', natural: '380101', module: 'Revenue'},
        {description: 'MSHW - CONTRACTS REVENUE', natural: '380104', module: 'Revenue'},
        {description: 'SFTW DEPLOYMENT REV NETSIM-OTHER', natural: '380200', module: 'Revenue'},
        {description: 'SFTW DEPLOYMENT REV ADI', natural: '380201', module: 'Revenue'},
        {description: 'PASS THROUGH REVENUE', natural: '380300', module: 'Revenue'},
        {description: 'PS - CONSULTING SERVICES', natural: '390330', module: 'Revenue'},
        {description: 'HW PRODUCT COGS', natural: '410003', module: 'COGS'},
        {description: 'PRODUCT COGS IEMP', natural: '410004', module: 'COGS'},
        {description: 'SERVICE COGS ONDEMAND', natural: '470001', module: 'COGS'},
        {description: 'SOFTWARE COGS FOTOPUNCH', natural: '480001', module: 'COGS'},
        {description: 'Salary & Wages', natural: '510001', module: 'Payroll'},
        {description: 'COMP & BENEFIT COMS', natural: '510002', module: 'Payroll'},
        {description: 'COMP & BENEFIT BONUS ADI SUPPORT', natural: '510003', module: 'Payroll'},
        {description: 'COMP & BENEFIT OPTIONS', natural: '510005', module: 'Payroll'},
        {description: 'PAYROLL TAXES', natural: '510007', module: 'Payroll'},
        {description: 'COMP & BENEFIT GROUP INS', natural: '510009', module: 'Payroll'},
        {description: '401K MATCHING', natural: '510012', module: 'Payroll'},
        {description: 'COMP & BENEFIT PLACEMENT', natural: '510014', module: 'Payroll'},
        {description: 'COMP & BENEFIT RELO COSTS SALES HEADQUARTERS', natural: '510015', module: 'Payroll'},
        {description: 'COMP & BENEFIT TRAIN & SEMINAR', natural: '510016', module: 'Payroll'},
        {description: 'COMP & BENEFIT - SEVERANCE', natural: '510017', module: 'Payroll'},
        {description: 'COMP & BENEFIT COFFEE & MEETING', natural: '510018', module: 'Payroll'},
        {description: 'COMP & BENEFIT DUES & SUBSCRIP', natural: '510019', module: 'Payroll'},
        {description: 'COMP & BENEFIT AWARDS & TAX-HUMAN RESOURCES', natural: '510020', module: 'Payroll'},
        {description: 'COMP & BENEFIT BUS MEETING EXP', natural: '510021', module: 'Payroll'},
        {description: 'TRAVEL & ENT AIR ADI SUPPORT', natural: '520001', module: 'Travel and Entertainment'},
        {description: 'TRAVEL & ENT AUTO MILEAGE, TAXI', natural: '520002', module: 'Travel and Entertainment'},
        {description: 'Travel & Ent- -', natural: '520003', module: 'Travel and Entertainment'},
        {description: 'Travel & Ent-Field Service', natural: '520004', module: 'Travel and Entertainment'},
        {description: 'TRAVEL & ENT AUTO RENTAL', natural: '520005', module: 'Travel and Entertainment'},
        {description: 'TRAVEL & ENT OTHER--AF SAAS OPS', natural: '520006', module: 'Travel and Entertainment'},
        {description: 'MARKETING TRINKETS', natural: '530001', module: 'Marketing'},
        {description: 'MARKETING ADVERTISING MARKETING', natural: '530002', module: 'Marketing'},
        {description: 'MARKETING SALES TOOLS MARKETING', natural: '530003', module: 'Marketing'},
        {description: 'MARKETING DESIGN SERVICES MARKETING', natural: '530004', module: 'Marketing'},
        {description: 'MARKETING RESEARCH MARKETING', natural: '530006', module: 'Marketing'},
        {description: 'Marketing Tradeshow Expense', natural: '530007', module: 'Marketing'},
        {description: 'MARKETING PR', natural: '530008', module: 'Marketing'},
        {description: 'MARKETING DEMAND/LEAD GENERATION MARKETING', natural: '530011', module: 'Marketing'},
        {description: 'SUPPLIES - MISC', natural: '540011', module: 'Operating Expenses'},
        {description: 'DEPRECIATION FIXED ASSETS IEMP COGS', natural: '550003', module: 'Fixed Asset'},
        {description: 'AMORTIZATION OF S&M INTANGIBLES', natural: '550004', module: 'Intangibles'},
        {description: 'FACILITIES RENT', natural: '560001', module: 'Rent & Utilities'},
        {description: 'FACILITIES UTILITIES', natural: '560002', module: 'Rent & Utilities'},
        {description: 'FACILITIES REPAIR & MAINT', natural: '560003', module: 'Rent & Utilities'},
        {description: 'FACILITIES BLDG - SEC EXP', natural: '560008', module: 'Rent & Utilities'},
        {description: 'TELECOM EXP VOICE', natural: '565001', module: 'Rent & Utilities'},
        {description: 'TELECOM EXP DATA', natural: '565002', module: 'Rent & Utilities'},
        {description: 'TELECOM EXP CELLULAR', natural: '565005', module: 'Rent & Utilities'},
        {description: 'EQUIP RENTAL', natural: '570001', module: 'Rent & Utilities'},
        {description: 'EQUIP REPAIR & MAINT', natural: '570002', module: 'Rent & Utilities'},
        {description: 'EQUIP EXPD', natural: '570003', module: 'Rent & Utilities'},
        {description: 'EQUIP SOFTWARE', natural: '570004', module: 'Rent & Utilities'},
        {description: 'Office supplies Duck', natural: '575001', module: 'Rent & Utilities'},
        {description: 'Supplies-PSNW', natural: '575002', module: 'Rent & Utilities'},
        {description: 'SUPPLIES - MISC', natural: '575006', module: 'Rent & Utilities'},
        {description: 'LEGAL OTHER CORP EXEC', natural: '590001', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES AUDIT FEES', natural: '590002', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES CONSULT ADI SUPPORT', natural: '590003', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES REGULATORY', natural: '590004', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES INTERNATIONAL FINANCE & ADM', natural: '590006', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES BOARD CORP EXEC', natural: '590007', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES FRANCHISE TAX', natural: '590010', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES PROPERTY TAX', natural: '590011', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES STATE INC', natural: '590012', module: 'Professional Fees'},
        {description: 'SALES TAX EXPENSE', natural: '590016', module: 'Tax'},
        {description: 'PROF, TAXES, FEES BANK FEES', natural: '590020', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES CHARITABLE GIFTS CORP EXEC', natural: '590022', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES LICENSES&FEES SALES HEADQUARTERS', natural: '590023', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES NON-DED GIFTS', natural: '590024', module: 'Professional Fees'},
        {description: 'PROF, TAXES, FEES-DED GIFTS', natural: '590026', module: 'Professional Fees'},
        {description: 'OTHER OPEX BAD DEBT', natural: '595001', module: 'Operating Expenses'},
        {description: 'OTHER OPEX DISCOUNTS TAKEN FINANCE & ADM', natural: '595002', module: 'Operating Expenses'},
        {description: 'OTHER OPEX PRINT & REPRO - AUSTIN', natural: '595003', module: 'Operating Expenses'},
        {description: 'Late Fee - Penalty Fee', natural: '595004', module: 'Penalties and Fees'},
        {description: 'OTHER EXPENSES', natural: '595006', module: 'Operating Expenses'},
        {description: 'OTHER OPEX INSUR', natural: '595007', module: 'Operating Expenses'},
        {description: 'OTHER INC/EXP MISC', natural: '610020', module: 'Operating Expenses'},
        {description: 'FOREIGN CURRENCY TRANSLATION', natural: '610030', module: 'Realized Gain/Loss'},
        {description: 'INT INCOME INTERCO INTEREST', natural: '620020', module: 'Interest'},
        {description: 'INT EXPENSE VENDOR CHARGE', natural: '620050', module: 'Interest'},
        {description: 'INT EXPENSE CREDIT CARD FEES', natural: '620055', module: 'Bank Fees'},
        {description: 'PENALTIES AND FEES', natural: '620060', module: 'Penalties and Fees'},
        {description: 'INT EXPENSE DEBT-One Time Costs-', natural: '620070', module: 'Interest'},
        {description: 'Interest Exp - Defer Finance Costs', natural: '620080', module: 'Interest'},
        {description: 'INCOME TAXES PROVISION FOR FEDERAL', natural: '630010', module: 'Tax'},
        {description: 'FOREIGN TAXES WITHHELD', natural: '630020', module: 'Tax'}
      ]);
    });
};
